name: bPermissions
version: 3.0.1a
author: codename_B
main: de.bananaco.permissions.Packages
commands:
  addpackage:
    usage: /<command> player package (world)
    permission: bpermissions.admin
    description: add a package entry to the database
  permissions:
    usage: /<command>
    permission: bpermissions.admin
permissions:
  bpermissions.admin:
    default: op
    description: use all bPermissions3 commands in one easy permission node